version: '3.8'

services:
  home-security:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    entrypoint: /app/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure

  db:
    env_file:
      - .env
    image: postgres
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - "POSTGRES_DB=${DB_NAME}"
        - "POSTGRES_HOST_AUTH_METHOD=trust"
        - "POSTGRES_USER=${DB_USER}"
        - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
        - 5432:5432
volumes:
  postgres_data: