# Generated by Django 5.0.6 on 2024-07-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='home_security.building'),
        ),
    ]
